-- IRIS Protocol — schema pointer
--
-- The schema is defined by the ordered migrations in db/migrations/, which are
-- the source of truth. This file exists so the layout matches
-- IRIS_BUILD_PROMPT v2.0 section 4; it is deliberately not a second copy of the
-- DDL, because a hand-maintained duplicate drifts.
--
-- To apply the schema to a running database:
--
--     make db-migrate                       # or:
--     psql "$DATABASE_URL" -f db/migrations/0001_init.sql
--
-- To dump the live schema for inspection or diffing:
--
--     pg_dump --schema-only --no-owner "$DATABASE_URL" > /tmp/iris.schema.sql
--
-- docker compose mounts db/migrations/ and db/seed/ into the Postgres
-- container's entrypoint, so a fresh `docker compose up` applies both
-- automatically on first boot.
